# Generated by Django 4.2.7 on 2023-11-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('breakfast', models.JSONField()),
                ('lunch', models.JSONField()),
                ('dinner', models.JSONField()),
            ],
        ),
    ]
