# Generated by Django 4.2.7 on 2023-11-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_dashboard', '0002_foodrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrating',
            name='rating',
        ),
        migrations.AddField(
            model_name='foodrating',
            name='ratings',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
