# Generated by Django 4.2.7 on 2023-12-26 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_dashboard', '0005_remove_foodrating_ratings_foodrating_rating_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='foodrating',
            name='rating_range',
        ),
        migrations.AlterField(
            model_name='foodrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
