# Generated by Django 4.2.7 on 2024-01-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_dashboard', '0006_remove_foodrating_rating_range_alter_foodrating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='lunch',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('meal', models.CharField(max_length=255)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_dashboard.menu')),
            ],
        ),
    ]
