# Generated by Django 4.2.7 on 2023-11-27 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaint_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
