# Generated by Django 4.2.7 on 2023-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bits_id',
            field=models.CharField(default='', max_length=13),
        ),
    ]
